### ISSUE TITLE
shareyourpaper does not accept some email addresses that are valid

### ISSUE THREAD

**Issue by JosephMcArthur** [oaworks/discussion#1776]
**Is your feature request related to a problem? Please describe.**

See message titled `shareyourpaper does not accept email address`.

**Describe the solution you'd like**

For the email address to be accepted. Depend on if this is "one of those things that will happen a small amount of the time" or some bug that's pop up and can be solved, more may be required.

**Comment by markmacgillivray** [comment]
Funnily enough the mailgun validator tells us that both the addresses for the person in question are not valid, which is why we don't accept them. If I turn off mailbox validation (which means mailgun tries to check that the mail address itself actually exists at the service, not just that it is a valid address for that service) then the two addresses do pass the validation test - but turning that off could increase the number of invalid addresses that we accept. Also, if we do turn that off, I think we'd be better just running a regex check on the email and not using the mailgun validator at all, given that they now charge us for use of it, and if it's not performing adequately let's just drop it.

Let me know what you want.

**Comment by JosephMcArthur** [comment]
I'm happy to turn this off and replace with a regex.

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
This should be finished tonight or Monday.

**Comment by markmacgillivray** [comment]
Done, checked on dev and live with the problem emails, solved.
