### ISSUE TITLE
Deposits are failing on live & dev

### ISSUE THREAD

**Issue by JosephMcArthur** [oaworks/discussion#1809]
**Describe the bug**

When files are being uploaded they're failing and showing

`Sorry, we were not able to deposit this paper for you. Please try contacting your library directly`

The deposit API is turning `400` on live & dev.

**To Reproduce**
1. https://dev.shareyourpaper.org/10.1063/1.523376
2. enter an email
3. Upload [77JMP DOI 10.1063_1.523376 (1).pdf](https://github.com/oaworks/discussion/files/6538034/77JMP.DOI.10.1063_1.523376.1.pdf)

**Expected behavior**

Should allow deposit.

Seems to be affecting many articles

**Comment by markmacgillivray** [comment]
On dev I have it working of sorts, it does not error but it does not allow deposit. It says "an earlier version is needed". It is saying that because the file check is unable to properly read that PDF - it's one where most of the text is not actually text, it's an image scan, but there IS some text in it. So the answer the dev system now gives appears to be correct as much as it ever would have been. Are you sure this file is one you expect the system would accept for deposit? I don't see how it could be, at the moment.

**Comment by JosephMcArthur** [comment]
That very well may be the expected response given the system limitations.

This journal allows published pdfs though so it's quite possible we could
turn off version checking as long as we can confirm it's the correct paper
- which I think we could given the DOI is in the file name. Probably best
to discuss that in another issue though.

If you've made a fix can we push it to dev?

**Comment by JosephMcArthur** [comment]
Live sorry. Push live.

Also, it seems like Ghost isn't picking up this issue. What was broken, and
what test should we add?

**Comment by markmacgillivray** [comment]
Does ghost do a file deposit as a test and was it still succeeding? If so then the issue was probably only to do with certain types of file. The deposit endpoint intentionally throws a 400 if it couldn't get a good match on the provided metadata, but I've relaxed that now so it runs through anyway. That was less likely to happen previously because the initial find would have been stored in the same system, but now that find/permissions are on the new system while deposit is on the old, perhaps it is more likely to cause a 400. So, that's the quick fix for it now, and once we switch deposit to the new system it won't be possible any more anyway.

I'll update live just now.

**Comment by JosephMcArthur** [comment]
Makes sense. 

I've just deposited the above paper on dev via the normal admin deposit, so it looks like we're in better shape there. Will circle back to tidy up loose ends here later.

**Comment by markmacgillivray** [comment]
live is updated, and now gets the same response for this paper as dev did, so seems to be fine.
