### ISSUE TITLE
Mailgun not delivering to help@openaccessbutton.org

### ISSUE THREAD

**Issue by JosephMcArthur** [oaworks/discussion#1813]
See: https://app.mailgun.com/app/sending/domains/mg.openaccessbutton.org/logs?event=failed-permanent&date_from=2021-06-08T00%3A00%3A00.000Z&date_to=2021-06-14T23%3A59%3A59.999Z&sort=datetime%3Adesc`

Is there a way to fix this in Mailgun that you know of @markmacgillivray?

**Comment by markmacgillivray** [comment]
It seems I can't login without a token, presumably being sent to Joe. The last time I had to do this for I think Joes address, it was because mailgun had suppressed it due to it bouncing. If that has also happened to the "help" address, then it can be unsuppressed. On the dashboard for the domain, click the "suppressions" option. Search for the email, and somewhere there is an option to unsuppress it if it has been suppressed due to previous bounces. Or I don't mind doing it if Joe can set up mailgun email forwarding from his account to mine, so I can get logged in to that account.

**Comment by markmacgillivray** [comment]
Done
