### ISSUE TITLE
InstantILL error referring to ScienceDirect

### ISSUE THREAD

**Issue by JosephMcArthur** [oaworks/discussion#1814]
Sent over email, logging here.

> Just one article this time - a patron reported an error in a link from InstantILL to the full text in ScienceDirect. I verified that we do have the article in our holdings and the link resolver URL is working. 
> 
> The article is “Quadruple sulfur isotope biosignatures from terrestrial Mars analogue systems,” DOI 10.1016/j.gca.2021.06.007
> 
> InstantILL detects the article in our holdings https://www.ulib.iupui.edu/ill?title=Quadruple%20sulfur%20isotope%20biosignatures%20from%20terrestrial%20Mars%20analogue%20systems
> 
> And generates this link:
> 
> https://www.ulib.iupui.edu/cgi-bin/proxy.pl?url=https://www.sciencedirect.com/science/link?ref_val_fmt=info:ofi/fmt:kev:mtx:journal&amp;svc_val_fmt=info:ofi/fmt:kev:mtx:sch_srv&amp;rfr_dat=saltver:1&amp;rfr_dat=origin:SERIALSSOL&amp;ctx_enc=info:ofi/enc:UTF-8&amp;ctx_ver=Z39.88-2> 
> ScienceDirect then responds with this error message: “Sorry, we seem to have hit a problem processing your request
> 
> You could try reloading the page, or perhaps leave it a few minutes then try again. If that doesn’t solve the problem, our support team will be happy to help.
> 
> Error code: GURL-3”
>> 
> For comparison, the URL directly from the link resolver is:
> 
> https://rx8kl6yf4x.search.serialssolutions.com/?sid=google&auinit=A&aulast=Moreras-Marti&atitle=Quadruple+sulfur+isotope+biosignatures+from+terrestrial+Mars+analogue+systems&id=doi:10.1016/j.gca.2021.06.007

Is this also something you've looked at @markmacgillivray?

**Comment by markmacgillivray** [comment]
When I try it now, it seems to work fine for me, unless I am missing something. The link we find now isn't the same as the one given above, which does still give the GURL-3 error at sciencedirect. So, I'd theorise that this was a problem at the sciencedirect/serialssolutions side of things if so. If you go via that ulib IUPUI page linked above now, and follow the link instantill gives, it goes to an IUPUI proxy page which contains the sciencedirect link to proceed to after login. If I go straight to that link without login, the link works without sciencedirect showing the error. Do you still get that error if you login? I'd guess not, since I can see the error on the old link without login. But if you do, then it could be the auth proxy service at IUPUI is damaging that forwarding link somehow. However I'd first suggest just trying again, this is probably working now.

**Comment by snipejaeg** [comment]
Thanks for looking into this, Mark. I think you're right, the new URL being generated is working as expected. There are a few differences between the link in the error ticket & what I'm seeing now, but it looks like the key is that it's including the DOI at the end ("&rft_id=info:doi/10.1016/j.gca.2021.06.007") - when I remove this string from the new URL, I get the error message again.

But since it's working as expected now, that's more "file away for future reference" than anything that needs action now, I think.

Thanks!

**Comment by JosephMcArthur** [comment]
Thanks Mike!!
