### ISSUE TITLE
Deposit to Zenodo not respecting license

### ISSUE THREAD

**Issue by JosephMcArthur** [oaworks/discussion#1834]
**Describe the bug**

When depositing to Zenodo we expect that the license permissions provides will be matched in Zenodo. However, at least in some cases this seems to not be happening.

I've found this example:
* https://zenodo.org/record/5503549#.YWl-OdmZNqt
* https://api.openaccessbutton.org/permissions?doi=10.1016/j.mimet.2021.106322

**To Reproduce**

I haven't had time to replicate this myself.

**Expected behavior**

The article should've been licensed CC-BY-NC-ND.

**Comment by markmacgillivray** [comment]
Nothing new to report here, but looking at the example, permissions and zenodo appear to show the same licence to me...

**Comment by JosephMcArthur** [comment]
Huh. Okay, well, look at this pair:

* https://zenodo.org/record/5656187
* https://api.openaccessbutton.org/permissions?doi=10.1007/s12098-020-03616-1

**Comment by markmacgillivray** [comment]
I've done further investigating of this and it is due to the difference between old and new systems again. We will have to update the old system to take account of this, or finish the work to move deposit to the new system. I'd suggest we finish the deposit work rather than fixing this in the old system.

**Comment by JosephMcArthur** [comment]
Sure thing
