### ISSUE TITLE
GDPR Compliance

### ISSUE THREAD

**Issue by JosephMcArthur** [oaworks/discussion#960]
Doctored text from GDPR & OAB discussion had over email

- [x] We should add back in the "delete account" functionality. If we add it back in, we can also make it clear in our terms that people can remove themselves entirely from our system by just deleting their account and not using our service any more. We should decide what this means for requests created by someone who deletes their account. We should remove those requests or at least remove the details of who created them. We'll need it to have a little "are you sure, doing this will do X" pop up dialog and confirmation (incase of accidental clicking). @markmacgillivray to engineer, Joe to write copy. 
- [x] make our statistics page private
- [ ] Location data should likely be deleted, as it is not in use and unlikely to be in use in future
- [x] Review / remove admins with high access but little activity 
- [x] Remove code that fingerprints devices, but doesn't improve security yet
- [x] Allow users to get a copy of all the data we have about them from /account. This can just be an option to email us, but we have to be able to provide in 30 days. Considering this might also involve Zendesk / Analytics etc it may be best to implement simply as a email request.
- [ ] ~change terms opt in into a unfilled tickbox again. Re-auth everyone to new terms once released.~
- [ ] Do we really need to keep IPs?

**Comment by markmacgillivray** [comment]
Make private to admin only

**Comment by JosephMcArthur** [comment]
@markmacgillivray can you give me an update here please?

**Comment by markmacgillivray** [comment]
This is also part of the #1464 placeholder issue - the import script from old to new will make sure that any old data containing IPs or locations will be chucked when the import runs. The decision about IP addresses was that the new system does keep them but only in logs, and we can dump old logs any time we want without impacting any other part of the service. Having them there in the first place is useful for debugging certain problems, and would be necessary if we have to do certain kinds of management / usage mitigation, so decided to at least keep them in logs for a while.

I guess I may as well close this one since we have the other issue as a placeholder for it.
